### ISSUE TITLE
Not able to install luamongo in windows 7

### ISSUE THREAD

**Issue by swaroopsp** [moai/luamongo#36]
C:\Users\s.panigrahi.ext>luarocks install "https://raw.githubusercontent.com/moai/luamongo/master/rockspec/luamongo-scm-0.rockspec

Error: LuaRocks 2.0.2 bug (please report at luarocks-developers@lists.luaforge.net).
...\Program Files (x86)\Lua\5.1\lua/luarocks\fs\lua.lua:526: attempt to concatenate local 'err' (a nil value)
stack traceback:
        ...\Program Files (x86)\Lua\5.1\lua/luarocks\fs\lua.lua:526: in function 'download'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:33: in function 'fetch_url'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:70: in function 'fetch_url_at_temp_dir'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\fetch.lua:231: in function 'load_rockspec'
        ...:\Program Files (x86)\Lua\5.1\lua/luarocks\build.lua:101: in function <...:\Program Files (x86)\Lua\5.1\lua/luarocks\build.lua:97>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        [C]: in function 'xpcall'
        ...am Files (x86)\Lua\5.1\lua\luarocks\command_line.lua:143: in function 'run_command'
        C:\Program Files (x86)\Lua\5.1\luarocks.lua:20: in main chunk
        [C]: ?

**Comment by swaroopsp** [comment]
Sorry. I am not very familiar with LUA. I found the LUA 5.1 for windows in 
https://code.google.com/p/luaforwindows/downloads/list

The lua 5.2 seems to be available for linux not windows. 

And i tried to download v0.2, but i am not sure how to use it.
Do u have any set of instructions

**Comment by pakozm** [comment]
Unfortunatelly, I'm not an expert to tell you how to install luamongo in windows... 
However, the steps to install luamongo (in any platform) are:

1. Install the mongo c++ driver, its legacy-v0.9.0: https://github.com/mongodb/mongo-cxx-driver/
2. Compile luamongo.
3. Install luamongo at any place in `packages.path` Lua string.

Let me know if you success with it. I will be very glad to know the steps necessary to install it in windows, just to write them in the wiki.

**Comment by pakozm** [comment]
Closing this dead thread.
