### ISSUE TITLE
LuaJIT

### ISSUE THREAD

**Issue by iryont** [moai/luamongo#38]
Hey guys

I'm not sure why Lua 5.2 is required for this project. It's basically one library which is currently forcing people to resign from performance benefits of LuaJIT and go for unnecessary Lua 5.2

Is there any real reason behind Lua 5.2?

**Comment by pakozm** [comment]
How are you doing with the Lua 5.1 plus Lua 5.2 support in luamongo? I'm thinking in opening a branch to work on this issue, in case you couldn't continue with it.

**Comment by zaibon** [comment]
I'll would also be interested to use luamongo with luajit. @iryont can you share the modifications  you had to do in order to make luamongo works under luajit ?

**Comment by pakozm** [comment]
A pull request will be accepted with the condition it supports Lua 5.2 and Lua 5.1 in an automatic way. I think it is possible to do a minor change to makefiles to support the use of Lua 5.1 or Lua 5.2 depending in what is available in the system.

**Comment by iryont** [comment]
Hey guys

I can surely upload the changes, but all I did was to change code back to Lua 5.1. It wouldn't be that hard to make it work for both versions, in fact I'm sure we can create a branch for it. I will make a poll request once I fix the code - I was a bit busy with other things, so I didn't work on it yet, I'm really sorry for the delay.

**Comment by pakozm** [comment]
Nice! :-) So, just open the pull whenever you can and we can discuss the "automatic thing" for the Makefile. I will open a branch now to work on it, and make the pull to the new opened branch.

**Comment by iryont** [comment]
#39

**Comment by pakozm** [comment]
Well done :-)
