### ISSUE TITLE
auto_reconnect feature not working

### ISSUE THREAD

**Issue by Requilence** [moai/luamongo#43]
Hi! Thank you for the great driver. Works flawlessly except auto_reconnect declared in the docs. 
It is just keeping return "Connection error" on assert (or nil without). So I need to manually check for nil, reconnect and repeat the query.

**Comment by pakozm** [comment]
Problem solved at commit 03184a398ddf365bf2d52f39d61c358a16a81ba1
Thanks for noticing this problem :-)

**Comment by Requilence** [comment]
👍🏼 Thank you!
