### ISSUE TITLE
add new release 

### ISSUE THREAD

**Issue by antirek** [moai/luamongo#44]
Fix please your code in new release. 
With work revision 4 my docker image don't work properly, but with current master all ok. I want make good Dockerfile and check only freezed code in version semantic. Thanks.

**Comment by pakozm** [comment]
This was easy to be done ;-) So you have next work revision: v0.4.5

**Comment by antirek** [comment]
Francisco, great and hot thanks from far and cold Krasnoyarsk, Russia : )
